package solutions.manage_plots.models;

import static starters.manage_plots.Utils.isExist;
import static starters.manage_plots.Utils.resizeArr;

public class Street {
    private final String name;
    private final String city;
    private Plot[] plots;
    private int numOfPlots;

    public Street(String name, String city, int initialNumberOfPlots) {
        this.name = name;
        this.city = city;
        this.plots = new Plot[initialNumberOfPlots]; // Initialize with capacity
    }

    public String getName() {
        return name;
    }

    public String getCity() {
        return city;
    }

    public int getNumOfPlots() {
        return numOfPlots;
    }

    /**
     * Adds a plot to the street.
     * @param plot The plot to add.
     */
    public void addPlot(Plot plot) {
        if (plot == null) {
            throw new IllegalArgumentException("Cannot add a null plot.");
        }
        if (isExist(plots, numOfPlots, plot)){
            throw new RuntimeException("Plot already exist.");
        }
        if (plots.length == numOfPlots){
            plots = (Plot[]) resizeArr(plots);
        }
        this.plots[numOfPlots++] = plot;
        // System.out.println("Added plot " + plot.getSerialNumber() + " to " + this.name + ".");
    }

    /**
     * Calculates the total municipal tax revenue generated by all applicable plots on this street.
     * Applies polymorphism to call calculateMunicipalTax() on each plot.
     * @return The total municipal tax revenue for the street.
     */
    public double getMunicipalTaxRevenue() {
        double totalRevenue = 0;
        for (int i = 0; i < numOfPlots; i++) {
            totalRevenue += plots[i].calculateMunicipalTax();
        }
        return totalRevenue;
    }

    /**
     * Calculates the total water usage in cubic meters for all applicable plots on this street.
     * Applies polymorphism to call calculateWaterUsage() on each plot.
     * @return The total water usage in cubic meters for the street.
     */
    public double getWaterUsageCuM() {
        double totalWaterUsage = 0;
        for (int i = 0; i < numOfPlots; i++) {
            totalWaterUsage += plots[i].calculateWaterUsage();
        }
        return totalWaterUsage;
    }

    @Override
    public String toString() {
        return "Street [name=" + name + ", city=" + city + ", number of plots=" + numOfPlots + "]";
    }

    public String showPlots() {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < numOfPlots; i++) {
            sb.append(plots[i]).append("\n");
        }
        return sb.toString();
    }
}
